### ISSUE TITLE
Add a discussion section on this repo

### ISSUE THREAD

**Issue by johnspeny** [icppWorld/icpp-pro#19]
Interesting project, I have run a sample and it works just as written in the docs. I have so many questions that those looking to use Icpp may want to easily find in the discussion sections.

**Comment by icppWorld** [comment]
Hi @johnspeny ,
Thank you for that feedback.

We have a C++ community at OpenChat that you can join it via this link:

https://oc.app/community/cklkv-3aaaa-aaaar-ar7uq-cai/?ref=6e3y2-4yaaa-aaaaf-araya-cai


Looking forward to see you there !

**Comment by icppWorld** [comment]
@johnspeny ,
In addition to the OpenChat community, it is probably useful to also have a discussion section right here. 
I opened it.

Thanks again for the suggestion.
